### ISSUE TITLE
Release the latest main branch that includes custom url change

### ISSUE THREAD

**Issue by panpan2557** [tomaskazatel/baserow-client#7]
Hello! First of all, thank you for your amazing SDK. I'm really excited to use it. But, I ended up debugging and found that it works only for Baserow cloud (via installing it from npmjs though). I found that the latest main code already includes this [PR](https://github.com/tomaskazatel/baserow-client/pull/5) but the npmjs still recognizes v.0.1.0 as latest release. Can you help release main branch again so that it includes the custom url changes? My workaround is to install the package directly from the Github repo. But it would be more convenient to have it on npmjs!

**Comment by tomaskazatel** [comment]
Thanks for your request. I just release version 0.3.0 with this changes. Thanks for your support.
